// Tout le contenu modifiable du portfolio est ici.
// Un projet "featured: true" apparaît dans le scroll horizontal, les autres dans l'archive.
// Chaque projet a sa page : projet.html?p=<slug>

export const profile = {
  firstName: 'Dylan',
  lastName: 'Belledent',
  role: 'Développeur full stack',
  email: 'dylanbelledent@gmail.com',
  location: 'Béziers, France',
  timezone: 'Europe/Paris',
  cv: 'assets/cv.pdf',
  socials: [
    { label: 'GitHub', url: 'https://github.com/dyzlek' },
    { label: 'LinkedIn', url: 'https://www.linkedin.com/in/dylan-belledent-18b35b341/' },
  ],
};

export const layers = [
  {
    name: 'Front',
    text: 'Interfaces rapides et animées, du site vitrine à la scène 3D dans le navigateur.',
    tags: ['HTML / CSS', 'JavaScript', 'Tailwind', 'Bootstrap', 'Three.js', 'A-Frame', 'Phaser', 'GSAP'],
  },
  {
    name: 'Back',
    text: 'API, bases de données, authentification, modules et plugins qui tiennent la route.',
    tags: ['PHP', 'SQL / MySQL', 'Node.js / Express', 'Python', 'C# / Unity', 'WordPress', 'PrestaShop'],
  },
  {
    name: 'Créa',
    text: 'Le côté MMI : maquettes, motion design et 3D, pour que le code ait aussi de la gueule.',
    tags: ['Figma', 'UI / UX', 'After Effects', 'Blender', 'Suite Adobe', 'Montage vidéo'],
  },
];

export const marquee = [
  'JavaScript', 'PHP', 'Three.js', 'Node.js', 'MySQL', 'Unity', 'PrestaShop',
  'WordPress', 'Tailwind', 'Figma', 'Blender', 'After Effects', 'Python', 'Git',
];

export const projects = [
  /* ---------------- Mis en avant ---------------- */
  {
    slug: 'sillon',
    featured: true,
    title: 'Sillon',
    year: '2026',
    category: 'Perso',
    kind: 'Lecteur de musique perso',
    summary: 'Mes sons sur mon propre serveur, un écran réduit au minimum et un visualiseur 3D qui danse sur la musique.',
    tags: ['Node.js', 'SQLite', 'Three.js', 'Web Audio'],
    color: '#FF5A2E',
    pattern: 'rings',
    cover: 'assets/sillon/sphere.webp',
    links: [{ label: 'Code source', url: 'https://github.com/dyzlek/sillon' }],
    intro: [
      'Un lecteur pour écouter ma musique depuis mon serveur, sans passer par une plateforme. Le serveur garde les fichiers et les envoie en streaming ; l’écran ne montre que le titre en cours, une ligne de progression et un nuage de particules qui réagit au son en direct.',
      'Toute la bibliothèque vit dans une base SQLite : titres, artistes, pochettes, durées, écoutes, et pour chaque son la suite de vues du visualiseur et leur rythme.',
    ],
    facts: [
      ['Serveur', 'Node.js sans framework, streaming par plages d’octets, dossier surveillé, envoi par glisser-déposer protégé par une clé'],
      ['Base', 'SQLite intégré à Node : bibliothèque, historique d’écoute, réglages du visualiseur par son'],
      ['Visualiseur', '8 400 particules Three.js, trois formes calculées sur le GPU et interpolées, pilotées par l’analyseur Web Audio'],
      ['Outils', 'Import d’un dossier avec association automatique des pochettes, édition de la base en ligne de commande'],
      ['Design', 'Même grammaire que ce portfolio : Archivo condensé, Geist Mono, grain, une seule couleur d’accent'],
    ],
    sections: [
      { title: 'Lecture', text: 'Le titre en grand, l’artiste et la pochette, des commandes en texte. La sphère se gonfle bande par bande : chaque latitude écoute une partie du spectre.', images: ['assets/sillon/sphere.webp'] },
      { title: 'Trois vues', text: 'L’anneau suit chaque fréquence autour du cercle ; le spectre est un paysage qui défile, chaque rangée étant un instant passé du morceau. Les vues s’enchaînent seules, selon la base, et plus tôt sur une montée de basses.', images: ['assets/sillon/anneau.webp', 'assets/sillon/spectre.webp'] },
      { title: 'Index', text: 'Tous les sons du serveur, avec le même effet au survol que l’index de ce portfolio. On y dépose aussi de nouveaux fichiers.', images: ['assets/sillon/index.webp'] },
    ],
  },
  {
    slug: 'photoprint-assistant',
    featured: true,
    title: 'Photoprint Assistant',
    year: '2026',
    category: 'Perso',
    kind: 'Module PrestaShop',
    summary: 'Upload, contrôle qualité en DPI, recadrage et prix par format pour les boutiques de tirages photo.',
    tags: ['PHP 8', 'PrestaShop 8/9', 'JavaScript', 'Smarty'],
    color: '#F2A7C3',
    pattern: 'grid',
    cover: 'assets/photoprint/fiche-produit.webp',
    links: [{ label: 'Code source', url: 'https://github.com/dyzlek/photoprint_assistant' }],
    intro: [
      'Un module PrestaShop pour les boutiques de tirages photo. Sur la fiche produit, le client choisit sa photo et un format, la recadre, puis voit en direct si la qualité suffit et combien coûte son tirage.',
      'Le défi : tout vérifier avant l’envoi (type, poids, dimensions, DPI effectifs pour le format et le recadrage choisis) et brancher le résultat sur le panier natif de PrestaShop, pour que chaque photo suive la commande jusqu’aux factures et au back-office.',
    ],
    facts: [
      ['Compatibilité', 'PrestaShop 8.0 à 9.x, PHP 8.1+'],
      ['Qualité', 'Vert ≥ 300 DPI, orange 150–299, rouge < 150 avec confirmation'],
      ['Recadrage', 'Cropper.js au ratio exact du format, portrait / paysage, rotation'],
      ['Prix', 'TTC par format + dégressif par quantité, mis à jour sans rechargement'],
      ['Sécurité', 'Jeton CSRF, type MIME réel vérifié côté serveur, noms aléatoires, dossier fermé'],
      ['Qualité du code', 'Tests JS et PHP, CI GitHub Actions, release zip automatique'],
    ],
    sections: [
      { title: 'Sur la fiche produit', text: 'Format, photo, recadrage, indicateur de qualité et prix dégressif, tout au même endroit. Pensé mobile d’abord, avec des boutons de 44 px.', images: ['assets/photoprint/fiche-produit.webp', 'assets/photoprint/fiche-produit-mobile.webp'] },
      { title: 'Contrôle qualité', text: 'Même format, photo de plus en plus petite : l’indicateur passe du vert au rouge. Le module prévient aussi quand un mauvais ratio coupe une grosse part de l’image.', images: ['assets/photoprint/qualite.webp', 'assets/photoprint/recadrage.webp'] },
      { title: 'Panier et back-office', text: 'Chaque photo devient une personnalisation PrestaShop avec sa ligne de panier. Dans la commande, un bloc « Tirages photo » donne l’aperçu, le recadrage, les DPI et l’original à télécharger.', images: ['assets/photoprint/panier.webp', 'assets/photoprint/commande-bo.webp', 'assets/photoprint/configuration.webp'] },
    ],
  },
  {
    slug: 'bloons-vr',
    featured: true,
    title: 'Bloons VR',
    year: '2026',
    category: 'Scolaire',
    kind: 'Jeu VR · SAÉ 501',
    status: 'En cours',
    summary: 'Tower defense en réalité virtuelle façon Bloons TD : arc en main, singes posés sur une maquette, bananes à récolter.',
    tags: ['Unity 6', 'C#', 'Meta Quest 3', 'Blender'],
    color: '#FFB547',
    pattern: 'rings',
    cover: 'assets/bloons/cabane-dehors.webp',
    links: [{ label: 'Code source', url: 'https://github.com/dyzlek/SAE501' }],
    intro: [
      'SAÉ de 3e année de BUT MMI : un jeu en réalité virtuelle sous Unity, en équipe de trois et en trois semaines. Tu es Quincy, tu tires à l’arc sur les ballons, tu poses tes singes à la main sur une maquette et tu ramasses tes bananes avant qu’elles pourrissent.',
      'Mon rôle : le hub (bibliothèque, plateau qui affiche la carte en direct, placement libre, fusion de singes), la carte en labyrinthe et les vagues de ballons, la fusion des trois prototypes de l’équipe, et toute l’organisation Git (branches, PR, tableau d’issues, journaux).',
    ],
    facts: [
      ['Équipe', '3 étudiants, encadrés par 4 enseignants'],
      ['Moteur', 'Unity 6 (URP), XR Interaction Toolkit, Meta Quest 3'],
      ['Boucle', 'Tirer à l’arc et placer ses singes pour arrêter des vagues de plus en plus solides'],
      ['Mécaniques', 'Fusion de singes, coffre à roulette et raretés, bananier qui produit et pourrit'],
      ['3D', 'Cabane du hub modélisée dans Blender par script Python'],
      ['Rendu', '13 novembre 2026'],
    ],
    sections: [
      { title: 'Le hub', text: 'Ma partie. Une cabane en rondins éclairée aux lanternes : on y est géant devant la maquette de la carte, qui montre la partie en direct. On pose ses singes à la main, on en fusionne deux identiques pour monter de niveau (halo doré), on achète des améliorations au comptoir. Tout le texte est posé sur le décor, sur des ardoises et des plaques, jamais collé au visage.', images: ['assets/bloons/hub-plateau.webp', 'assets/bloons/fusion-doree.webp', 'assets/bloons/hub-comptoirs.webp', 'assets/bloons/hub-bananier.webp'] },
      { title: 'La carte et les vagues', text: 'Un labyrinthe à taille réelle, 10 vagues écrites à l’avance jusqu’au dirigeable rouge. Le hub et la carte restent chargés tous les deux : la vague continue quand on revient à la cabane, et le même joueur VR passe d’un niveau à l’autre.', images: ['assets/bloons/labyrinthe.webp', 'assets/bloons/arc-visee.webp', 'assets/bloons/ballons.webp', 'assets/bloons/tableau-vague.webp'] },
      { title: 'Coffres et singes', text: 'Le coffre de Nicolas s’ouvre sur une roulette façon CS, avec 7 raretés qui se débloquent au fil des ouvertures. Les singes gagnés atterrissent dans la bibliothèque du hub, prêts à être posés sur le plateau.', images: ['assets/bloons/coffre-roulette.webp', 'assets/bloons/bibliotheque-singes.webp'] },
      { title: 'Du prototype au jeu', text: 'J’ai fusionné les trois prototypes de l’équipe en un seul projet. Le hub est passé d’un cercle de cubes gris à une cabane modélisée dans Blender par un script Python (une seule source, régénérable), posée au milieu des montagnes.', images: ['assets/bloons/proto-hub-cercle.webp', 'assets/bloons/schema-hub.webp', 'assets/bloons/cabane-v3.webp', 'assets/bloons/cabane-v4.webp'] },
      { title: 'Travailler à plusieurs', text: 'Jamais deux personnes sur la même scène : tout passe par des prefabs, une branche par tâche, des pull requests relues, un tableau d’issues GitHub, et un build casque chaque vendredi.', images: ['assets/bloons/horizon.webp'] },
    ],
  },
  {
    slug: 'image-seo-pro',
    featured: true,
    title: 'Image SEO Pro',
    year: '2026',
    category: 'Perso',
    kind: 'Plugin WordPress SEO',
    status: 'En cours',
    summary: 'Des copies WebP et AVIF sans toucher aux originaux, et des textes alternatifs écrits par une IA de vision.',
    tags: ['PHP', 'WordPress', 'JavaScript', 'IA'],
    color: '#C8F169',
    pattern: 'bars',
    cover: 'assets/imageseo/tableau-de-bord.webp',
    links: [{ label: 'Code source', url: 'https://github.com/dyzlek/image-seo-pro' }],
    intro: [
      'Un plugin WordPress qui allège les images et complète les textes alternatifs. Chaque image reçoit une copie WebP et AVIF créée à côté de l’original, qui n’est jamais modifié. Les alt manquants se remplissent avec une IA de vision (Ollama en local, ou une API compatible OpenAI) ou à partir du nom du fichier.',
      'La version 2.0 est une réécriture complète de ma première version (WebP Converter Pro), qui supprimait les originaux et ne vérifiait pas les droits sur ses actions AJAX. Né de mon travail SEO sur le site d’Easy Mobility.',
    ],
    facts: [
      ['Formats', 'WebP et AVIF pour l’image et chaque miniature ; une copie plus lourde n’est pas gardée'],
      ['Moteur', 'Imagick ou GD, choisi selon le serveur, avec repli automatique'],
      ['Affichage', 'Balise &lt;picture&gt; sur les contenus et les images du thème, sans casser la mise en page'],
      ['Textes alternatifs', 'Liste des images sans alt, édition en ligne, suggestion IA, remplissage en masse'],
      ['Outils', 'Commandes WP-CLI, traduction française, désinstallation propre'],
      ['Qualité', 'Tests d’intégration dans un vrai WordPress, CI GitHub avec GD et Imagick, PHP 7.4 à 8.4'],
    ],
    sections: [
      { title: 'Tableau de bord', text: 'Le bilan en un coup d’œil (images optimisées, poids économisé, images sans alt) et ce que le serveur sait produire. Un bouton optimise toute la médiathèque, avec barre de progression et bouton d’arrêt.', images: ['assets/imageseo/tableau-de-bord.webp'] },
      { title: 'Images', text: 'Pour chaque image : poids d’origine, copies WebP et AVIF et gain réel (ici −85 % et −92 %). Une image peut être refaite ou restaurée seule.', images: ['assets/imageseo/images.webp'] },
      { title: 'Textes alternatifs', text: 'Édition en ligne avec compteur de 125 caractères, suggestion par IA ou depuis le nom du fichier. L’IA reçoit une miniature d’environ 1 024 px, écrit dans la langue du site et connaît le titre de la page où l’image est utilisée.', images: ['assets/imageseo/textes-alternatifs.webp'] },
    ],
  },
  {
    slug: 'kc-catalogue',
    featured: true,
    title: 'KC Catalogue',
    year: '2026',
    category: 'Perso',
    kind: 'Plateforme gaming',
    summary: 'Collection de jeux vidéo, reviews, profils sociaux et mini-jeux, branchée sur l’API IGDB.',
    tags: ['Node.js', 'Express', 'MySQL', 'IGDB API'],
    color: '#9AC4F8',
    cover: 'assets/kcc/kcc-home.webp',
    links: [{ label: 'Code source', url: 'https://github.com/dyzlek/KCC' }],
    intro: [
      'KC Catalogue est né d’une frustration simple : aucune plateforme ne centralisait vraiment ma collection de jeux, mes envies et mes avis. Alors je l’ai construite.',
      'Le site récupère en direct les données de l’API IGDB (couvertures, notes, dates, captures). On gère sa bibliothèque avec des statuts, on note sur 10, on écrit des reviews et on suit d’autres joueurs. C’est le projet où j’ai le plus appris côté back.',
    ],
    facts: [
      ['Back-end', 'Node.js, Express 5, architecture MVC'],
      ['Données', 'MySQL (mysql2/promise), des dizaines de jointures'],
      ['Rendu', 'Nunjucks côté serveur, CSS vanilla responsive'],
      ['Auth', 'Passport.js avec connexion Steam, bcrypt, sessions'],
      ['Divers', 'Nodemailer (mot de passe oublié), Multer (avatars, bannières)'],
    ],
    sections: [
      { title: 'Accueil et catalogue', text: 'Un jeu mis en avant via IGDB, une navigation par plateforme, genre ou période, et une grille avec tri par popularité, date ou note.', images: ['assets/kcc/kcc-home.webp', 'assets/kcc/kcc-catalogue.webp'] },
      { title: 'Fiche jeu et communauté', text: 'Synopsis, plateformes, médias, note de la presse contre note des joueurs, et les reviews de la communauté.', images: ['assets/kcc/kcc-game-detail.webp', 'assets/kcc/kcc-game-media.webp', 'assets/kcc/kcc-reviews.webp'] },
      { title: 'Higher or Lower', text: 'Un mini-jeu : deux jeux s’affrontent, il faut deviner lequel a le plus de joueurs simultanés sur Steam.', images: ['assets/kcc/kcc-higher-lower-landing.webp', 'assets/kcc/kcc-higher-lower-game.webp'] },
    ],
  },
  {
    slug: 'easy-mobility',
    featured: true,
    title: 'Easy Mobility',
    year: '2026',
    category: 'Pro',
    kind: 'Refonte & SEO',
    summary: 'Refonte complète et stratégie SEO pour le distributeur français des solutions de mobilité AACURAT.',
    tags: ['PHP', 'Tailwind CSS', 'PHPMailer', 'SEO'],
    color: '#FFD84D',
    cover: 'assets/easymobility/easymobility-home.webp',
    links: [{ label: 'Voir le site', url: 'https://www.easymobility.fr' }],
    intro: [
      'Easy Mobility est le distributeur exclusif en France des solutions de mobilité et de levage AACURAT. J’ai pris en charge la refonte complète du site, de la structure jusqu’à la mise en ligne.',
      'Le site devait être professionnel, accessible et convaincant pour une clientèle qui cherche du matériel médical spécialisé. En parallèle, j’ai mené toute la stratégie SEO : audit technique, balises, méta-descriptions, URLs et suivi dans Google Search Console.',
    ],
    facts: [
      ['Back-end', 'PHP vanilla, architecture multi-pages sur mesure, sans CMS'],
      ['Style', 'Tailwind CSS compilé, responsive'],
      ['Formulaires', 'Contact et devis avec PHPMailer, anti-spam, validation serveur'],
      ['SEO', 'Audit technique, optimisation on-page, Search Console'],
      ['Performance', 'Assets optimisés et compressés'],
    ],
    sections: [
      { title: 'Accueil', text: 'Un hero épuré avec une accroche directe, le produit phare mis en avant et un double appel à l’action.', images: ['assets/easymobility/easymobility-home.webp', 'assets/easymobility/easymobility-solutions.webp'] },
      { title: 'Catalogue et fiches produit', text: 'Chaque produit a sa page : fiche technique, caractéristiques clés, documentation PDF et accès direct au devis. Le contenu est structuré pour le SEO.', images: ['assets/easymobility/easymobility-catalogue.webp', 'assets/easymobility/easymobility-product.webp', 'assets/easymobility/easymobility-quisommesnous.webp'] },
    ],
  },
  {
    slug: 'webar-beziers',
    featured: true,
    title: 'WebAR Béziers',
    year: '2025',
    category: 'Scolaire',
    kind: 'Réalité augmentée',
    summary: 'Une affiche qui prend vie au smartphone pour raconter l’enseignement supérieur à Béziers.',
    tags: ['A-Frame', 'MindAR', 'Tailwind', 'JavaScript'],
    color: '#7FE3D0',
    cover: 'assets/ar-poster.webp',
    links: [
      { label: 'Expérience 3D', url: 'demos/ar-beziers/index.html' },
      { label: 'Mode AR', url: 'demos/ar-beziers/ar.html' },
      { label: 'Code source', url: 'https://github.com/dyzlek/S303' },
    ],
    intro: [
      'Comment rendre des données brutes attractives ? On est partis de tableaux statistiques et de PDF denses sur l’enseignement supérieur à Béziers, pour en faire une expérience narrative en réalité augmentée.',
      'L’utilisateur ne lit plus les statistiques, il les explore en 3D en scannant l’affiche. Projet réalisé avec Lina Missaoui.',
    ],
    facts: [
      ['Scène 3D', 'A-Frame'],
      ['Tracking', 'MindAR (reconnaissance d’image dans le navigateur)'],
      ['Interface', 'Tailwind CSS, JavaScript vanilla'],
    ],
    sections: [
      { title: 'De la source à l’AR', text: 'Des documents PDF à une affiche test servant de zone de tracking, jusqu’au rendu final immersif.', images: ['assets/ar-process.webp'] },
      { title: 'L’affiche cible', text: 'Conçue pour être reconnue par MindAR, elle sert d’ancrage à tous les éléments virtuels.', images: ['assets/ar-poster.webp'] },
      { title: 'Les sources', text: 'Les pages de données d’origine, à partir desquelles on a écrit le scénario et les visualisations.', images: ['assets/ar-source-1.webp', 'assets/ar-source-2.webp', 'assets/ar-source-3.webp'] },
    ],
  },

  /* ---------------- Archive ---------------- */
  {
    slug: 'marathon-2026',
    title: 'Marathon MMI 2026',
    year: '2026',
    category: 'Scolaire',
    kind: 'Site WordPress en 4 jours',
    summary: '« Arlett », un coffee shop à Béziers : site vitrine complet en équipe de 6, en 4 jours.',
    tags: ['WordPress', 'Elementor', 'CSS'],
    color: '#E9C9A8',
    cover: 'assets/marathon/marathon-home.webp',
    links: [{ label: 'Voir le site', url: 'https://web-mmi.iutbeziers.fr/marathon_2026/marathon_2026_12/wordpress/' }],
    intro: [
      'Le Marathon MMI, c’est une semaine intensive où les 2e année créent une identité complète autour d’un sujet imposé. 4 jours de production, une équipe de 6, un résultat concret.',
      'Sur « Arlett », j’étais en charge du développement web et de l’intégration : traduire la direction artistique de mes coéquipiers en un site WordPress fonctionnel et responsive, en très peu de temps.',
    ],
    facts: [['CMS', 'WordPress + Elementor'], ['Finitions', 'CSS sur mesure pour coller à la DA'], ['Équipe', '6 personnes, collaboration avec les designers']],
    sections: [{ title: 'Aperçu du site', text: '', images: ['assets/marathon/marathon-home.webp', 'assets/marathon/marathon-1.webp', 'assets/marathon/marathon-2.webp', 'assets/marathon/marathon-4.webp'] }],
  },
  {
    slug: 'lego-collection',
    title: 'LEGO Collection',
    year: '2025',
    category: 'Scolaire',
    kind: 'SAÉ 203 · Full stack',
    summary: 'Gestion de collection de sets LEGO : comptes, wishlist, commentaires, notes et back-office.',
    tags: ['PHP', 'MySQL', 'MVC', 'Bootstrap'],
    color: '#FF8A3D',
    cover: 'assets/lego/lego-hero.webp',
    links: [{ label: 'Voir le site', url: 'https://web-mmi2.iutbeziers.fr/~dylan.belledent/projet/SAE203/' }],
    intro: [
      'Projet universitaire : concevoir un site dynamique en PHP avec une base de données. J’ai développé une application complète pour les fans de LEGO.',
      'Inscription, gestion de sa collection, wishlist, commentaires et notes, import de données CSV et gestion des utilisateurs côté admin.',
    ],
    facts: [['Back-end', 'PHP / MySQL, architecture MVC'], ['Sécurité', 'Mots de passe hachés, protection XSS et injection SQL'], ['Interface', 'Bootstrap, responsive']],
    sections: [{ title: 'Fonctionnalités', text: '', images: ['assets/lego/lego-hero.webp', 'assets/lego/lego-set.webp', 'assets/lego/lego-detail.webp', 'assets/lego/lego-3.webp', 'assets/lego/lego-7.webp'] }],
  },
  {
    slug: 'spoti-stats',
    title: 'Spoti-Stats',
    year: '2025',
    category: 'Perso',
    kind: 'Dashboard data',
    summary: 'Tes artistes, titres et genres préférés, visualisés via l’API Spotify.',
    tags: ['JavaScript', 'API Spotify', 'OAuth 2.0', 'Chart.js'],
    color: '#5BE38A',
    cover: 'assets/spoti-stats/dashboard.webp',
    links: [{ label: 'Voir le site', url: 'demos/spoti-stats/index.html' }],
    intro: [
      'Un dashboard pour visualiser ses habitudes d’écoute Spotify : artistes les plus écoutés, titres préférés, genres dominants.',
      'Les données arrivent en direct de l’API Web de Spotify, avec une connexion sécurisée en OAuth 2.0.',
    ],
    facts: [['Front', 'HTML, CSS, JavaScript ES6+'], ['Data viz', 'Chart.js'], ['Auth', 'OAuth 2.0 Spotify']],
    sections: [{ title: 'Interface', text: 'Un design sombre qui reprend les codes de Spotify.', images: ['assets/spoti-stats/dashboard.webp', 'assets/spoti-stats/home.webp'] }],
  },
  {
    slug: 'summer-adventure',
    title: 'Summer Adventure',
    year: '2025',
    category: 'Scolaire',
    kind: 'Jeu vidéo coop',
    summary: 'Un jeu de plateforme à deux joueurs, développé avec Phaser.',
    tags: ['Phaser 3', 'JavaScript', 'Game design'],
    color: '#8FD3FF',
    cover: 'assets/summer-adventure/gameplay-1.webp',
    links: [{ label: 'Jouer', url: 'demos/summer-adventure/index.html' }],
    intro: [
      'Un projet pour apprendre Phaser et approfondir JavaScript : un jeu complet, jouable à deux, avec des mécaniques de plateforme et de coopération.',
    ],
    facts: [['Moteur', 'Phaser 3'], ['Code', 'Physique, collisions, logique de jeu en JS'], ['Niveaux', 'Tilemaps, sprites et animations']],
    sections: [{ title: 'Aperçu', text: 'Les deux joueurs doivent s’entraider pour passer les obstacles et atteindre la fin du niveau.', images: ['assets/summer-adventure/gameplay-1.webp', 'assets/summer-adventure/gameplay-2.webp'] }],
  },
  {
    slug: 'moodtracku',
    title: 'MoodTrackU',
    year: '2025',
    category: 'Scolaire',
    kind: 'UX / UI',
    summary: 'Maquette et prototype Figma d’une app de suivi d’humeur et de bien-être.',
    tags: ['Figma', 'UX Research', 'Prototypage'],
    color: '#B9E4C9',
    cover: 'assets/moodtracku/moodtracku-home.webp',
    links: [{ label: 'Prototype Figma', url: 'https://www.figma.com/design/tk6ngfGqVo90AiOzE7QBMB/MoodTrackU?node-id=0-1&t=ccPlD6QI8EmMlYWY-1' }],
    intro: [
      'Conception UX/UI sur Figma : une maquette complète et un prototype interactif avec au moins deux parcours utilisateurs.',
      'Le travail a porté sur la cohérence visuelle, l’ergonomie des interactions et la fluidité de la navigation.',
    ],
    facts: [['UX', 'User flows'], ['UI', 'Écrans haute fidélité'], ['Prototype', 'Interactions et animations avancées']],
    sections: [{ title: 'Maquettes', text: '', images: ['assets/moodtracku/moodtracku-home.webp', 'assets/moodtracku/moodtracku-1.webp', 'assets/moodtracku/moodtracku-2.webp', 'assets/moodtracku/moodtracku-5.webp'] }],
  },
  {
    slug: 'motion-design',
    title: 'Motion design',
    year: '2025',
    category: 'Scolaire',
    kind: 'CV vidéo & showreel',
    summary: 'CV vidéo, générique de film, typo animée et défis chronométrés.',
    tags: ['After Effects', 'Premiere Pro', 'Blender'],
    color: '#C9B6FF',
    pattern: 'waves',
    cover: null,
    coverVideo: 'assets/motion-design/film-credits.mp4',
    links: [],
    intro: [
      'Le motion design, pour moi, c’est une façon de raconter une histoire et de capter l’attention. Ici : mon CV vidéo pour l’alternance, des exercices sous contrainte de temps et des créations plus libres.',
    ],
    facts: [['Animation', 'After Effects (2D, compositing, effets)'], ['Montage', 'Premiere Pro / DaVinci, étalonnage, sound design'], ['3D', 'Blender intégré au flux vidéo']],
    sections: [
      { title: 'Générique de film', text: 'After Effects + Blender : un générique complet, avec un vrai travail sur les transitions et l’atmosphère.', videos: ['assets/motion-design/film-credits.mp4'] },
      { title: 'CV vidéo', text: 'Se vendre en vidéo : rythme, transitions fluides et message clair.', videos: ['assets/motion-design/cv-video.mp4'] },
      { title: 'Exercice « Vox »', text: 'Typographie animée et synchronisation audio précise.', videos: ['assets/motion-design/vox-exercise.mp4'] },
      { title: 'Promotion alternance et défi 1 h', text: 'Une vidéo de promotion de l’alternance, et une reproduction technique réalisée en une heure.', videos: ['assets/motion-design/alternance-promo.mp4', 'assets/motion-design/repro-b2.mp4'] },
    ],
  },
  {
    slug: 'food-festival',
    title: 'Food Festival',
    year: '2025',
    category: 'Scolaire',
    kind: 'Identité visuelle',
    summary: 'L’aligot en mode cartoon : affiche et flyer pour un festival culinaire.',
    tags: ['Illustrator', 'Photoshop', 'InDesign'],
    color: '#FFE08A',
    cover: 'assets/affiche_page-0001.webp',
    links: [{ label: 'L’affiche (PDF)', url: 'assets/affiche.pdf' }, { label: 'Le flyer (PDF)', url: 'assets/bronchure.pdf' }],
    intro: [
      'Réinventer l’identité d’un festival culinaire, avec un sujet et un style tirés au sort : l’aligot, en cartoon.',
      'Pas seulement « faire joli » : restructurer l’information pour qu’elle se lise d’un coup d’œil, dans un univers ludique.',
    ],
    facts: [['Illustration', 'Illustrator, flat design vectoriel'], ['Textures', 'Photoshop'], ['Mise en page', 'InDesign, A5 recto / verso']],
    sections: [
      { title: 'Avant / après', text: 'À gauche, l’affiche d’origine fournie au tirage ; à droite, ma proposition.', images: ['assets/7-aligot-saucisse.jpg.webp', 'assets/affiche_page-0001.webp'] },
      { title: 'Le flyer', text: 'Un plan détaillé et les infos pratiques, sans surcharger le visuel.', images: ['assets/bronchure_page-0001.webp', 'assets/bronchure_page-0002.webp'] },
    ],
  },
  {
    slug: 'smiley-solution',
    title: 'Smiley Solution',
    year: '2025',
    category: 'Scolaire',
    kind: 'Marathon MMI 2025',
    summary: 'Mon premier marathon : site WordPress et carte de visite, en 4 jours et en équipe.',
    tags: ['WordPress', 'Print'],
    color: '#FFD23F',
    cover: 'assets/smiley/smiley-home.webp',
    links: [{ label: 'Voir le site', url: 'https://web-mmi.iutbeziers.fr/marathon_2025/marathon_2025_11/wordpress/' }],
    intro: [
      'En première année, il fallait imaginer une solution (« Smiley Solution ») et tout son univers en 4 jours. J’ai participé au site WordPress et conçu la carte de visite de l’entreprise.',
    ],
    facts: [['Web', 'Montage des pages sur WordPress'], ['Print', 'Carte de visite recto / verso'], ['Équipe', 'Coordination avec les pôles design et com']],
    sections: [{ title: 'Aperçu', text: '', images: ['assets/smiley/smiley-home.webp', 'assets/smiley/smiley-1.webp', 'assets/smiley/smiley-card-verso.webp'] }],
  },
];
